// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDzpZIeEt2UKM9V8D2rvXeMvcm-5WBOWU',
    appId: '1:979546323814:web:87db84004e5bc978d4a6a7',
    messagingSenderId: '979546323814',
    projectId: 'newsapp-b46f9',
    authDomain: 'newsapp-b46f9.firebaseapp.com',
    storageBucket: 'newsapp-b46f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-2n_b92KAHbUxryhnYr4h3T66LYlHtTU',
    appId: '1:979546323814:android:9072128a9fcc12c7d4a6a7',
    messagingSenderId: '979546323814',
    projectId: 'newsapp-b46f9',
    storageBucket: 'newsapp-b46f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQY4RfnGHbZEms3IXnN9Gm_tpOvMTQ7A',
    appId: '1:979546323814:ios:6fc91c398e52f7c9d4a6a7',
    messagingSenderId: '979546323814',
    projectId: 'newsapp-b46f9',
    storageBucket: 'newsapp-b46f9.appspot.com',
    iosClientId: '979546323814-33o2vbrt6n8f2p4iqk54brsjk20cupb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDQY4RfnGHbZEms3IXnN9Gm_tpOvMTQ7A',
    appId: '1:979546323814:ios:f892fad2cf62c733d4a6a7',
    messagingSenderId: '979546323814',
    projectId: 'newsapp-b46f9',
    storageBucket: 'newsapp-b46f9.appspot.com',
    iosClientId: '979546323814-hdg40vddhbdee8klpqnfvr1gootimijv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsBlog.RunnerTests',
  );
}
